"""Retirado

Revision ID: 52aecfa88d7b
Revises: e1e171caf664
Create Date: 2023-01-14 17:47:05.704761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52aecfa88d7b'
down_revision = 'e1e171caf664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
