"""add campanhas

Revision ID: 7708364131ff
Revises: ea47d59e3997
Create Date: 2023-01-17 10:39:44.735153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7708364131ff'
down_revision = 'ea47d59e3997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('donor', sa.String(length=255), nullable=False),
    sa.Column('finality', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campanhas')
    # ### end Alembic commands ###
