"""Add Campanhas

Revision ID: ea47d59e3997
Revises: 8bfff5b49893
Create Date: 2023-01-16 22:43:52.665908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea47d59e3997'
down_revision = '8bfff5b49893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('donor', sa.String(length=255), nullable=False),
    sa.Column('finality', sa.Boolean(), nullable=False),
    sa.Column('goal', sa.Numeric(precision=19, scale=9), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campanhas')
    # ### end Alembic commands ###
